import React from 'react';
import { formatCurrency } from '../../utils/currency';

const TransactionList = ({ transactions = [], pharmacyName, onDelete }) => {
  const getTypeClass = (type) => {
    switch(type) {
      case 'income': return 'success';
      case 'expense': return 'warning';
      case 'withdrawal': return 'danger';
      default: return '';
    }
  };

  const handlePrint = (tx) => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Please allow pop-ups to print receipts.');
      return;
    }

    const receiptHtml = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Transaction Receipt</title>
        <style>
          body { 
            font-family: Arial, sans-serif; 
            margin: 0; 
            padding: 20px; 
            display: flex;
            justify-content: center;
            background: #f0f0f0;
          }
          .receipt-container {
            max-width: 400px;
            width: 100%;
          }
          .receipt { 
            border: 1px solid #ddd; 
            padding: 20px; 
            background: white;
            position: relative;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
          }
          .watermark {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%) rotate(-30deg);
            font-size: 40px;
            font-weight: bold;
            color: rgba(0,0,0,0.05);
            white-space: nowrap;
            z-index: 0;
            pointer-events: none;
            user-select: none;
            width: 100%;
            text-align: center;
          }
          .header { 
            text-align: center; 
            margin-bottom: 20px; 
            position: relative;
            z-index: 1;
          }
          .header h2 { margin: 0; color: #333; }
          .header p { margin: 5px 0; color: #666; }
          .details { 
            width: 100%; 
            border-collapse: collapse; 
            position: relative;
            z-index: 1;
          }
          .details td { 
            padding: 8px; 
            border-bottom: 1px solid #eee; 
          }
          .details tr:last-child td { border-bottom: none; }
          .label { font-weight: bold; color: #555; }
          .footer { 
            text-align: center; 
            margin-top: 20px; 
            color: #777; 
            font-size: 12px;
            position: relative;
            z-index: 1;
          }
          .badge {
            padding: 4px 8px;
            border-radius: 12px;
            font-size: 12px;
            font-weight: 500;
            text-transform: capitalize;
          }
          .badge.success { background-color: #d4edda; color: #155724; }
          .badge.warning { background-color: #fff3cd; color: #856404; }
          .badge.danger { background-color: #f8d7da; color: #721c24; }
          hr { margin: 20px 0; border: 0; border-top: 1px solid #ddd; }
          .generated-by {
            font-size: 10px;
            color: #999;
            margin-top: 5px;
          }
          @media print {
            body { background: white; padding: 0; }
            .receipt-container { max-width: 100%; }
            .receipt { box-shadow: none; border: 1px solid #000; }
          }
        </style>
      </head>
      <body>
        <div class="receipt-container">
          <div class="receipt">
            <div class="watermark">${pharmacyName || 'Pharmacy'}</div>
            <div class="header">
              <h2>${pharmacyName || 'Pharmacy'}</h2>
              <p>Official Receipt</p>
            </div>
            <table class="details">
              <tr><td class="label">Date:</td><td>${new Date(tx.date).toLocaleString()}</td></tr>
              <tr><td class="label">Type:</td><td><span class="badge ${getTypeClass(tx.type)}">${tx.type}</span></td></tr>
              <tr><td class="label">Description:</td><td>${tx.description}</td></tr>
              <tr><td class="label">Amount:</td><td>${formatCurrency(tx.amount)}</td></tr>
              <tr><td class="label">Transaction ID:</td><td>${tx._id}</td></tr>
              <tr><td class="label">Recorded by:</td><td>${tx.createdBy?.name || 'System'}</td></tr>
            </table>
            <div class="footer">
              <hr />
              <p>${pharmacyName || 'Pharmacy'}</p>
              <p>${new Date().toLocaleDateString()}</p>
              <p class="generated-by">Generated by PharmaSys</p>
            </div>
          </div>
        </div>
        <script>window.onload = function() { window.print(); window.close(); }</script>
      </body>
      </html>
    `;

    printWindow.document.write(receiptHtml);
    printWindow.document.close();
  };

  return (
    <table className="data-table" style={{ marginTop: '20px' }}>
      <thead>
        <tr>
          <th>Date</th>
          <th>Type</th>
          <th>Description</th>
          <th>Amount</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {transactions.length === 0 ? (
          <tr><td colSpan="5">No transactions found</td></tr>
        ) : (
          transactions.map(tx => (
            <tr key={tx._id}>
              <td>{new Date(tx.date).toLocaleDateString()}</td>
              <td><span className={`badge ${getTypeClass(tx.type)}`}>{tx.type}</span></td>
              <td>{tx.description}</td>
              <td>{formatCurrency(tx.amount)}</td>
              <td>
                <button className="secondary" onClick={() => handlePrint(tx)}>Print</button>
                <button className="danger" onClick={() => onDelete(tx._id)}>Delete</button>
              </td>
            </tr>
          ))
        )}
      </tbody>
    </table>
  );
};

export default TransactionList;