const PharmacySetting = require('../models/PharmacySetting');

/**
 * Generate a printable HTML document for a receipt
 * @param {Object} transaction - Transaction object
 * @param {Object} settings - Pharmacy settings (if not provided, fetched)
 * @returns {string} HTML string
 */
const generateReceiptHTML = async (transaction, settings = null) => {
  if (!settings) settings = await PharmacySetting.getSingleton();
  const date = new Date(transaction.createdAt).toLocaleString();
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Receipt</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 2rem; }
        .watermark {
          position: fixed;
          top: 50%;
          left: 50%;
          transform: translate(-50%, -50%) rotate(-45deg);
          opacity: 0.1;
          font-size: 5rem;
          white-space: nowrap;
          pointer-events: none;
          z-index: 1000;
        }
        .header { text-align: center; margin-bottom: 2rem; }
        .details { margin: 1rem 0; }
        .total { font-weight: bold; margin-top: 1rem; }
        .footer { margin-top: 2rem; text-align: center; font-size: 12px; color: gray; }
        @media print {
          body { margin: 0; }
          .watermark { opacity: 0.2; }
        }
      </style>
    </head>
    <body>
      ${settings.watermarkEnabled ? `<div class="watermark">${settings.name}</div>` : ''}
      <div class="header">
        <h1>${settings.name}</h1>
        <p>${settings.address}<br>${settings.phone} | ${settings.email}</p>
        <h3>Receipt</h3>
      </div>
      <div class="details">
        <p><strong>Transaction ID:</strong> ${transaction._id}</p>
        <p><strong>Date:</strong> ${date}</p>
        <p><strong>Type:</strong> ${transaction.type}</p>
        <p><strong>Reference:</strong> ${transaction.reference || '—'}</p>
        <p><strong>Payment Method:</strong> ${transaction.paymentMethod}</p>
        <p class="total"><strong>Amount:</strong> ${settings.currency} ${transaction.amount.toFixed(2)}</p>
      </div>
      <div class="footer">
        <p>${settings.name} – Official Receipt</p>
        <p>Generated: ${new Date().toLocaleString()}</p>
        <p>Powered by PharmaSys</p>
      </div>
    </body>
    </html>
  `;
};

/**
 * Generate a printable report HTML with watermark and footer
 * @param {string} title - Report title
 * @param {Array} data - Array of objects to display
 * @param {Array} columns - Column definitions [{key, label}]
 * @param {Object} settings - Pharmacy settings
 * @param {Object} user - The logged-in user (optional)
 * @returns {string} HTML string
 */
const generateReportHTML = async (title, data, columns, settings = null, user = null) => {
  if (!settings) settings = await PharmacySetting.getSingleton();
  const userName = user ? user.username : 'System';
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 2rem; }
        .watermark {
          position: fixed;
          top: 50%;
          left: 50%;
          transform: translate(-50%, -50%) rotate(-45deg);
          opacity: 0.1;
          font-size: 5rem;
          white-space: nowrap;
          pointer-events: none;
        }
        h1, h2 { text-align: center; }
        table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .footer { margin-top: 2rem; text-align: center; font-size: 12px; color: gray; }
        @media print { .watermark { opacity: 0.2; } }
      </style>
    </head>
    <body>
      ${settings.watermarkEnabled ? `<div class="watermark">${settings.name}</div>` : ''}
      <h1>${settings.name}</h1>
      <h2>${title}</h2>
      <p><strong>Generated on:</strong> ${new Date().toLocaleString()}</p>
      <p><strong>Generated by:</strong> ${userName}</p>
      <table>
        <thead>
          <tr>${columns.map(col => `<th>${col.label}</th>`).join('')}</tr>
        </thead>
        <tbody>
          ${data.map(row => `
            <tr>${columns.map(col => `<td>${row[col.key] ?? ''}</td>`).join('')}</tr>
          `).join('')}
        </tbody>
      </table>
      <div class="footer">
        <p>${settings.name} – Official ${title}</p>
        <p>Powered by PharmaSys</p>
      </div>
    </body>
    </html>
  `;
};

module.exports = { generateReceiptHTML, generateReportHTML };